    anim_TD = TextDrawCreate(419.000000, 420.000122, "~w~press ~b~~h~enter ~w~to stop animation");
    TextDrawLetterSize(anim_TD, 0.310499, 1.923556);
    TextDrawAlignment(anim_TD, 1);
    TextDrawColor(anim_TD, -1);
    TextDrawSetShadow(anim_TD, 0);
    TextDrawSetOutline(anim_TD, 1);
    TextDrawBackgroundColor(anim_TD, 51);
    TextDrawFont(anim_TD, 2);
    TextDrawSetProportional(anim_TD, 1);