    logotype_td[0] = TextDrawCreate(553.500000, 21.155534, "ROLEPLAY");
    TextDrawLetterSize(logotype_td[0], 0.239999, 1.848886);
    TextDrawAlignment(logotype_td[0], 1);
    TextDrawColor(logotype_td[0], -1);
    TextDrawSetShadow(logotype_td[0], 0);
    TextDrawSetOutline(logotype_td[0], 1);
    TextDrawBackgroundColor(logotype_td[0], 51);
    TextDrawFont(logotype_td[0], 2);
    TextDrawSetProportional(logotype_td[0], 1);

    logotype_td[1] = TextDrawCreate(566.000000, 9.088874, "nigva");
    TextDrawLetterSize(logotype_td[1], 0.300500, 1.880000);
    TextDrawAlignment(logotype_td[1], 1);
    TextDrawColor(logotype_td[1], -1);
    TextDrawSetShadow(logotype_td[1], 0);
    TextDrawSetOutline(logotype_td[1], 1);
    TextDrawBackgroundColor(logotype_td[1], 51);
    TextDrawFont(logotype_td[1], 2);
    TextDrawSetProportional(logotype_td[1], 1);

    logotype_td[2] = TextDrawCreate(552.500000, 0.133319, "u");
    TextDrawLetterSize(logotype_td[2], 0.881500, 2.825778);
    TextDrawAlignment(logotype_td[2], 1);
    TextDrawColor(logotype_td[2], 65535);
    TextDrawSetShadow(logotype_td[2], 0);
    TextDrawSetOutline(logotype_td[2], 1);
    TextDrawBackgroundColor(logotype_td[2], 51);
    TextDrawFont(logotype_td[2], 0);
    TextDrawSetProportional(logotype_td[2], 1);

    logotype_td[3] = TextDrawCreate(541.000000, 3.111111, "mp_unigva-pack:logo");
    TextDrawLetterSize(logotype_td[3], 0.000000, 0.000000);
    TextDrawTextSize(logotype_td[3], 99.500000, 54.133331);
    TextDrawAlignment(logotype_td[3], 1);
    TextDrawColor(logotype_td[3], -1);
    TextDrawSetShadow(logotype_td[3], 0);
    TextDrawSetOutline(logotype_td[3], 0);
    TextDrawFont(logotype_td[3], 4);

    // logotype_td[3] = TextDrawCreate(538.500000, 2.488892, "mp_unigva-pack:logotype");
    // TextDrawLetterSize(logotype_td[3], 0.000000, 0.000000);
    // TextDrawTextSize(logotype_td[3], 88.500000, 51.022201);
    // TextDrawAlignment(logotype_td[3], 1);
    // TextDrawColor(logotype_td[3], -1);
    // TextDrawSetShadow(logotype_td[3], 0);
    // TextDrawSetOutline(logotype_td[3], 0);
    // TextDrawFont(logotype_td[3], 4);